#!/usr/bin/env sh

echo "Building..."

mkdir -p dist/
cp -r css dist/css

pandoc presentation/**.md\
  -o dist/index.html\
  -t revealjs\
  -s\
  --template template/index.html\
  -V highlightjs\
  -V highlightjs-theme:zenburn\
  -V transition=fade\
  -L revealjs-codeblock.lua\
  --css css/avenga.css\
  -i
